apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootmongo
  strategy:
    type: Recreate
  template:
    metadata:
      name: spring-pod
      labels:
        app: springbootmongo
    spec:
      containers:
      - name: spring-container
        image: kalyankumar2025/springboot-mongo-app:13
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 400m
            memory: 512Mi
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongo-service #MongoDB Service Name
        - name: MONGO_DB_USERNAME
          value: prod
        - name: MONGO_DB_PASSWORD
          value: prod@123
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: springbootmongo
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: mongodb
   namespace: test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo-pod
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo-container
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: prod
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: prod@123
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service #Service Name Should be Given for MONGO_DB_HOSTNAME
  namespace: test-ns
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
